name: webdav_lastsync

on:
  schedule:
    - cron: '0 15,20 * * *'
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-18.04
    steps:
      - name: Fix
        run: |
          export SYNCFILE="lastsync.txt"
          export REMOTEFILE="https://dav.jianguoyun.com/dav/zotero/${SYNCFILE}"
          touch ${SYNCFILE}
          curl -u ${JIANGUO_EMAIL}:${JIANGUO_DAVPASS} -T ${SYNCFILE} ${REMOTEFILE}
        env:
          JIANGUO_EMAIL: ${{ secrets.JIANGUO_EMAIL }}
          JIANGUO_DAVPASS: ${{ secrets.JIANGUO_DAVPASS }}
